### ISSUE TITLE
Generate sliders in the settings for config keys that use FrooxEngine.RangeAttribute

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader#10]
ResoniteModSettings does this and it's pretty nice

![Screenshot 2024-05-10 223504](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/assets/14206961/73708b2e-d025-4476-993f-9bba212324ce)

**Comment by Banane9** [comment]
The Resonite Integration will already do this if you add a `ConfigKeyRange` component to your config key - but that's not directly available for RML mods of course.

**Comment by Banane9** [comment]
The Range attribute could be mapped to the components though, just like the `QuantityAttribute` could be mapped to `ConfigKeyQuantity`

**Comment by Nytra** [comment]
I have looked into this a bit, but I'm not sure where is the best place to check for the attributes, and I don't know how to correctly check which attributes the key has.

**Comment by Banane9** [comment]
You'll want to do that in `ModConfigurationDefinitionBuilder.ProcessField(field)`. You'll have to do `.GetCustomAttribute<RangeAttribute>()` and `.GetCustomAttribute<QuantityAttribute>()` on the field info to get if those attributes were placed on them. If not, it'll just be null. Then you just have to do some funny generic creation stuff like the SettingsDataFeedInjector does for some of the DataFeedItem generation to add the right components to the internal MonkeyLoader DefiningConfigKey of the ModConfigurationKeys.

**Comment by Nytra** [comment]
When logging the custom attributes of the key type I was just getting a bunch of these:

```
System.Runtime.CompilerServices.NullableAttribute
System.Runtime.CompilerServices.NullableContextAttribute
```

But I will give it another try

**Comment by Nytra** [comment]
Also how exactly does adding components work? Because this code won't compile:

```
fieldValue.UntypedKey.Components.Add(new ConfigKeyRange<float>());
```

**Comment by Nytra** [comment]
I figured it out:

```
((DefiningConfigKey<float>)fieldValue.UntypedKey).Components.Add(new ConfigKeyRange<float>());
```
