### ISSUE TITLE
Update version constant to `2.6.0`

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader#14]
Current value of `2.5.1` is wrong afaik

https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader/blob/b7b6464b3654ed35b61c299b5334e01c1c680c70/MonkeyLoader.GamePacks.ResoniteModLoader/ModLoader.cs#L30

**Comment by Nytra** [comment]
This causes ResoniteIKCulling to not patch anything because it thinks the version is out of date

`[INFO]  [MonkeyLoader|ResoniteIKCulling] Mod loader version out of date, please update to version 2.6.0 or later`

**Comment by Banane9** [comment]
Oh huh - we'll need to check if any of the public api changed then. I still wanted to make a tool for that since I didn't find one, but never got to it 😂

**Comment by Banane9** [comment]
Right... we were already doing the right version, but just didn't have it set in the constant 🤪
