### ISSUE TITLE
RML mods are seemingly being added twice

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader#18]
This line `Mod.Loader.AddMod(rmlMod);` is in the LoadMods method, but then it is being executed again in InitializeFrooxEnginePostfixAsync after the LoadMods call.

https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader/blob/7c692a32e434b01c4368c84698aa0de1a72c0247/MonkeyLoader.GamePacks.ResoniteModLoader/ModLoader.cs#L116

**Comment by Banane9** [comment]
It's not _really_ a problem because it uses a Set internally, but should be removed, yea lol. You can remove the one you linked to in the Initialize method.

**Comment by Banane9** [comment]
Can also move the ExitSubphase thing in the LoadMods method into a finally while you're at it :'D
