### ISSUE TITLE
Add a way to auto transfer configs from RML

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader#2]
If someone has existing RML mod configs and they transfer over to MonkeyLoader they will currently lose the configs.

There should be a way to transfer over existing configs automatically without needed to edit JSON files.

**Comment by Banane9** [comment]
I don't think copying the json is too hard for a one time process - and it is a lot of work to integrate RML's config parsing system too, for something that users will only use once.

But feel free to make it if you want it 😅

**Comment by l-2-j** [comment]
I guess closing issues which you have no plans to implement is a good way to communicate that intent... I just want to note though, that it does make it a bit harder to track what is and is not implemented though, since open/closed filtering has such a big priority by default on GH.

**Comment by Banane9** [comment]
> that it does make it a bit harder to track what is and is not implemented though, since open/closed filtering has such a big priority by default on GH.

Yea, GitHub is a bit pain with that :(
