### ISSUE TITLE
Add the ("Method {Method} has been patched by {Mod}") to debug logging

### ISSUE THREAD

**Issue by NepuShiro** [ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader#22]
Like in ResoniteModLoader which if there's multiple Mods patching the same method It will log the Mods patching that method or if debugging is enabled

https://github.com/resonite-modding-group/ResoniteModLoader/blob/01ea1c51f5dbeb8a739f73d5a6b967a000c348cc/ResoniteModLoader/ModLoader.cs#L101

**Comment by NepuShiro** [comment]
This doesn't exactly do what I meant, it doesn't log in the Resonite log at all only in the monkeyloader log which is bloated with a lot of useless info for me, and it also doesn't log the methods patched by a rml mod when its loaded. It only logs the conflicts of all rml mods after they're all loaded.

How rml does this is when an assembly is loaded it will then log the methods patched by that assembly inside of the resonite logs so it's easier for me and others to see, then it will log the conflicts after everything.

**Comment by Banane9** [comment]
It logs all the methods patched by the monkey when it is run and then also logs all conflicting patches after mods are started.

However, for this to work right with the reso integration, it does still require some code added there - as such, this is not quite done yet.

**Comment by Banane9** [comment]
![MonkeyLoader Console showing the potentially conflicting patches](https://github.com/user-attachments/assets/12cb0bae-9238-48e4-a874-8abfc3632b88)

There ;)

**Comment by NepuShiro** [comment]
This works for the Resonite Log, but this still doesn't log the non-conflicting patches from RML mods, it only does this for Monkeys

**Comment by Nytra** [comment]
RML mods are monkeys

**Comment by NepuShiro** [comment]
@Nytra Either way, the RML mods don't have the non-conflicting patches logged, only the Conflicting patches are logged.

[MonkeyLog_2024-11-22T22-48-45.log](https://github.com/user-attachments/files/17877221/MonkeyLog_2024-11-22T22-48-45.log)

RML mods begin init at line 3746-3782

**Comment by Banane9** [comment]
because we can't know the harmony instance / name of RML mods. we could look at all used ids, but that seems overkill for something native rml doesn't offer either.

**Comment by Nytra** [comment]
I think native RML does that if you are in Debug mode

**Comment by NepuShiro** [comment]
It's in the code that I linked in the orignal post, 

[NEPNEPSHIRO - 2024.10.29.1229 - 2024-11-22 17_44_03.log](https://github.com/user-attachments/files/17877525/NEPNEPSHIRO.-.2024.10.29.1229.-.2024-11-22.17_44_03.log)

Here's the same Reso Install with RML, this shows every non-conflicting patched method as well as conflicting ones (If I had any mods that patched the same thing)

**Comment by Banane9** [comment]
> I think native RML does that if you are in Debug mode

sorta, I guess. it jut lists all patched methods for debugging, even without the conflict.

**Comment by Banane9** [comment]
![grafik](https://github.com/user-attachments/assets/967cd682-ff04-4694-932b-2743f92c8a26)
