### ISSUE TITLE
Log messages from RML mods don't show the name of the mod

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader#6]
They should show the name of the mod.

**Comment by Banane9** [comment]
RML uses stack tracing to do it, which is always a nit pain so I didn't add that yet... But you can, if you want 😅

**Comment by Nytra** [comment]
So I should change ModLoader.Logger ?

**Comment by Banane9** [comment]
Yea, you'd have to change all the ModLoader.Logger references in the ResoniteMod class to use that ResoniteMod instance's Logger. Buuuut it requires analyzing the stack to check the calling assembly like RML.

**Comment by Nytra** [comment]
Oof, isn't there a way for each mod to override a string which tells the logger what its name should be?

**Comment by Banane9** [comment]
Would still require stack tracing, because due to the static method setup, there is no information about where the call might've come from 😅

In MonkeyLoader I got around this, by the static elements being on a generic class, so they're actually different per monkey.
